version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "zrosenbauer"
      - "sergiopalooza"
      - "polson136"
    default_labels:
      - "dependencies"
